sonar.projectKey=devops-showcase
sonar.projectName=DevOps Showcase
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,Dockerfile,requirements.txt

